#!/bin/sh /etc/rc.common

# Copyright 2020 Google LLC.
# SPDX-License-Identifier: Apache-2.0

USE_PROCD=1
START=99
STOP=1

start_service() {
	NETDEV=$(ip -o route get 119.29.29.29 | cut -f 5 -d " ")
	ethtool -K $NETDEV rx-udp-gro-forwarding on rx-gro-list off
	echo "tailscale_udp start" > /tmp/tailscale_udp.log
}

stop_service() {
	echo "tailscale_udp stop" > /tmp/tailscale_udp.log
}
